---
- hosts: machine
  become: true
  tasks:
  - name: install zabbix rpm source
    yum:
      name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
      state: installed
    when: ansible_distribution == 'CentOS'
  - name: donwload ubuntu deb
    get_url:
      url:  https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
      dest: /tmp/zabbix.deb
    when: ansible_distribution == 'Ubuntu'
  - name: install zabbix source
    apt:
      deb: /tmp/zabbix.deb
    when: ansible_distribution == 'Ubuntu'
  - name: install centos zabbix package
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - zabbix-proxy-mysql
      - zabbix-server-mysql
      - zabbix-web-mysql
    when: ansible_distribution == 'CentOS'
  - name: install ubuntu zabbix package
    apt:
      name: zabbix-agent
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'
  - name: modify zabbix config
    replace:
      path:  /etc/zabbix/zabbix_server.conf 
      regexp: DBUser=zabbix
      replace: DBUser=root
    when: ansible_distribution == 'CentOS'
  - name: import zabbix sql table
    shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uroot zabbix
    when: ansible_distribution == 'CentOS'
  - name: disable selinux
    selinux:
      state: disabled
    when: ansible_distribution == 'CentOS'
  - name: start zabbix-server
    systemd:
      name: zabbix-server
      state: started
    when: ansible_distribution == 'CentOS'
  - name: start zabbix-agent
    systemd:
      name: zabbix-agent
      state: started
    when: ansible_distribution == 'Ubuntu'
  - name: start mysql
    systemd:
      name: mysql
      state: started
    when: ansible_distribution == 'CentOS'
